name: Build Docs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        working-directory: docs
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Build docs
        working-directory: docs
        run: npm run build